SQL> SELECT DBMS_METADATA.GET_DDL('TABLE','USERS') FROM DUAL;

  CREATE TABLE "SMS"."USERS"
   (	"USER_ID" NUMBER,
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(255) NOT NULL ENABLE,
	"ROLE" VARCHAR2(20),
	"CREATED_AT" DATE DEFAULT SYSDATE,
	 PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

SQL> SELECT DBMS_METADATA.GET_DDL('TABLE','STUDENTS') FROM DUAL;

  CREATE TABLE "SMS"."STUDENTS"
   (	"STUDENT_ID" NUMBER,
	"FULL_NAME" VARCHAR2(100),
	"EMAIL" VARCHAR2(100),
	"PHONE" VARCHAR2(20),
	"CLASS_ID" NUMBER,
	 PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "FK_STUDENT_USER" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SMS"."USERS" ("USER_ID") ENABLE,
	 CONSTRAINT "FK_STUDENT_CLASS" FOREIGN KEY ("CLASS_ID")
	  REFERENCES "SMS"."CLASSES" ("CLASS_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

SQL> SELECT DBMS_METADATA.GET_DDL('TABLE','TEACHERS') FROM DUAL;

  CREATE TABLE "SMS"."TEACHERS"
   (	"TEACHER_ID" NUMBER,
	"FULL_NAME" VARCHAR2(100),
	"EMAIL" VARCHAR2(100),
	"PHONE" VARCHAR2(20),
	 PRIMARY KEY ("TEACHER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "FK_TEACHER_USER" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "SMS"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

SQL> SELECT DBMS_METADATA.GET_DDL('TABLE','CLASSES') FROM DUAL;

  CREATE TABLE "SMS"."CLASSES"
   (	"CLASS_ID" NUMBER,
	"CLASS_NAME" VARCHAR2(50),
	 PRIMARY KEY ("CLASS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

SQL> SELECT DBMS_METADATA.GET_DDL('TABLE','SUBJECTS') FROM DUAL;

  CREATE TABLE "SMS"."SUBJECTS"
   (	"SUBJECT_ID" NUMBER,
	"SUBJECT_NAME" VARCHAR2(100),
	"TEACHER_ID" NUMBER,
	 PRIMARY KEY ("SUBJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "FK_SUBJECT_TEACHER" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "SMS"."TEACHERS" ("TEACHER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

SQL> SELECT DBMS_METADATA.GET_DDL('TABLE','ENROLLMENTS') FROM DUAL;

  CREATE TABLE "SMS"."ENROLLMENTS"
   (	"ENROLLMENT_ID" NUMBER,
	"STUDENT_ID" NUMBER,
	"SUBJECT_ID" NUMBER,
	 PRIMARY KEY ("ENROLLMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "FK_ENROLL_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SMS"."STUDENTS" ("STUDENT_ID") ENABLE,
	 CONSTRAINT "FK_ENROLL_SUBJECT" FOREIGN KEY ("SUBJECT_ID")
	  REFERENCES "SMS"."SUBJECTS" ("SUBJECT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

SQL> SELECT DBMS_METADATA.GET_DDL('TABLE','ATTENDANCE') FROM DUAL;

  CREATE TABLE "SMS"."ATTENDANCE"
   (	"ATTENDANCE_ID" NUMBER,
	"STUDENT_ID" NUMBER,
	"SUBJECT_ID" NUMBER,
	"ATTENDANCE_DATE" DATE,
	"STATUS" VARCHAR2(10),
	 PRIMARY KEY ("ATTENDANCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "FK_ATT_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SMS"."STUDENTS" ("STUDENT_ID") ENABLE,
	 CONSTRAINT "FK_ATT_SUBJECT" FOREIGN KEY ("SUBJECT_ID")
	  REFERENCES "SMS"."SUBJECTS" ("SUBJECT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

SQL> SELECT DBMS_METADATA.GET_DDL('TABLE','MARKS') FROM DUAL;

  CREATE TABLE "SMS"."MARKS"
   (	"MARK_ID" NUMBER,
	"STUDENT_ID" NUMBER,
	"SUBJECT_ID" NUMBER,
	"MARKS" NUMBER(5,2),
	 PRIMARY KEY ("MARK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "FK_MARKS_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SMS"."STUDENTS" ("STUDENT_ID") ENABLE,
	 CONSTRAINT "FK_MARKS_SUBJECT" FOREIGN KEY ("SUBJECT_ID")
	  REFERENCES "SMS"."SUBJECTS" ("SUBJECT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

SQL> SPOOL OFF


